title: Cornell Scientific Computing and Numerics (SCAN) Seminar
email: bindel@cs.cornell.edu
description: >
  The SCAN seminar covers methods of scientific computing, analysis of
  their convergence properties and computational efficiency, and adaptation
  to specific applications.
baseurl: "/"
url: "https://cornell-scan.github.io"
future: true
exclude: ["Rakefile", "README.md"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "main"

# Build settings
markdown: kramdown
